name: CI
#  Kotlin CI workflow runs unit tests, builds artifact and uploads a code coverage report

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#  This workflow is run on pushes to master & every Pull Request,
#  if no *.kt files are changed it will pass without running as these are required checks
on:
  pull_request:
    paths:
      - "**/*.kt"
      - "*.gradle.kts"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"     # Push events to matching #.#.#, i.e. 1.0, 20.15.10
      - "[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching #.#.#-rc#, i.e. 1.0-rc1, 20.15.10-rc5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: fkneeland-figure/gha-kotlin-linter@v3

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test
      - uses: codecov/codecov-action@v3
        with:
          directory: "build/reports"

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Set tag version
        id: get_ver
        run: |
          echo "::set-output name=release_tag::${GITHUB_REF##*/}"
      - name: Assemble Dist
        uses: gradle/gradle-build-action@v2
        env:
          VERSION: ${{ steps.get_ver.outputs.release_tag }}
        with:
          # skip tests, we've already run them.
          arguments: clean -x test assembleDist
      - name: Checksum Dist
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checksumDist
      - uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          artifacts: "build/distributions/*"
          bodyFile: "RELEASE_CHANGELOG.md"
