name: Release
#  Release workflow builds and releases distribution artifacts.

#  This workflow is run on pushes to master & every Pull Request,
#  if no *.kt files are changed it will pass without running as these are required checks
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"     # Push events to matching #.#.#, i.e. 1.0, 20.15.10
      - "[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching #.#.#-rc#, i.e. 1.0-rc1, 20.15.10-rc5

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 11
      - name: Set tag version
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          PRE_RELEASE=false
          if [[ "$VERSION" =~ -rc ]]; then
            PRE_RELEASE=true
          fi
          echo "PRE_RELEASE=$PRE_RELEASE" >> $GITHUB_ENV
      - name: Defined tag version
        run: |
          echo VERSION=$VERSION
          echo PRE_RELEASE=$PRE_RELEASE
      - name: Build artifacts
        uses: gradle/gradle-build-action@v2.12.0
        with:
          arguments: distTar
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: ${{ env.PRE_RELEASE }}
          artifacts: "build/distributions/*"
          bodyFile: "RELEASE_CHANGELOG.md"
